import random
import string

def letter_swap(word): ...
def letter_insert(word): ...
def letter_drop(word): ...
def letter_duplicate(word): ...
def word_drop(text): ...
def word_swap(text): ...
def word_reorder(text): ...
def space_delete(text): ...
def lorem_gen(text): ...
def degrade_random_word(text, letter_func): ...
