"""
Create a set of familar phrases to analyze

This phrase set was generated by a AI chatbot when ask for:
"familiar phrases of 10 words or less"
"""

def get_familiar_phrases():
    return [
        "The quick brown fox jumps over the lazy dog.",
        "A stitch in time saves nine.",
        "Better late than never.",
        "Actions speak louder than words.",
        "All that glitters is not gold.",
        "Don't count your chickens before they hatch.",
        "Every cloud has a silver lining.",
        "Honesty is the best policy.",
        "Look before you leap.",
        "The early bird catches the worm.",
        "A penny saved is a penny earned.",
        "Practice makes perfect.",
        "Time and tide wait for no man.",
        "Too many cooks spoil the broth.",
        "When in Rome, do as the Romans do.",
        "You can’t judge a book by its cover.",
        "Beggars can’t be choosers.",
        "Birds of a feather flock together.",
        "Curiosity killed the cat.",
        "Don’t bite the hand that feeds you.",
        "If at first you don’t succeed, try and try again.",
        "The grass is always greener on the other side of the fence.",
        "A journey of a thousand miles begins with a single step.",
        "Don't put all your eggs in one basket.",
        "There's no such thing as a free lunch.",
        "Great minds think alike, but fools seldom differ.",
        "It takes two to tango in any real argument.",
        "You can't have your cake and eat it too.",
        "The squeaky wheel gets the grease every time.",
        "Many hands make light work."
    ]
